//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nerdsonsite_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public string Manufacturer { get; set; }
        public string Make { get; set; }
        public int Year { get; set; }
        public string Colour { get; set; }
        public int PassengerSeat { get; set; }
    }
}
